@endpoint=https://4jivy2zar3.execute-api.ap-southeast-2.amazonaws.com/prod

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces/
###

GET {{endpoint}}/spaces?spaceId=3b001bff-5d97-4ded-a917-9b72e770e70a
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "New Delhi",
    "name": "Home"
}
###
